topic "DBusScreenshot";
[i448;a25;kKO9;2 $$1,0#37138531426314131252341829483380:class]
[l288;2 $$2,2#27521748481378242620020725143825:desc]
[0 $$3,0#96390100711032703541132217272105:end]
[H6;0 $$4,0#05600065144404261032431302351956:begin]
[i448;a25;kKO9;2 $$5,0#37138531426314131252341829483370:item]
[l288;a4;*@5;1 $$6,6#70004532496200323422659154056402:requirement]
[l288;i1121;b17;O9;~~~.1408;2 $$7,0#10431211400427159095818037425705:param]
[i448;b42;O9;2 $$8,8#61672508125594000341940100500538:tparam]
[b42;2 $$9,9#13035079074754324216151401829390:normal]
[2 $$0,0#00000000000000000000000000000000:Default]
[{_} 
[ {{10000@(113.42.0) [s0;%% [*@7;4 DBusScreenshot]]}}&]
[s3; &]
[s1;:Upp`:`:DBusScreenshot: [@(0.0.255)3 class][3  ][*3 DBusScreenshot]&]
[s2;%% This class provides a native, non`-blocking interface to capture 
screenshots using the XDG Desktop Portal ([C@5 org.freedesktop.portal.Screenshot]) 
via D`-Bus.&]
[s3; &]
[ {{10000F(128)G(128)@1 [s0;%% [* Constructor detail]]}}&]
[s3; &]
[s5;:Upp`:`:DBusScreenshot`:`:DBusScreenshot`(DBusConnection`&`): [* DBusScreenshot](DB
usConnection[@(0.0.255) `&] [*@3 dbus])&]
[s2;%% Initializes the screenshot tool to operate over the specified 
[%-*@3 dbus] connection. The connection must already be established 
and the [^topic`:`/`/DBus`/src`/Upp`_DBusConnection`_en`-us`#Upp`:`:DBusConnection^ D
BusConnection] object must outlive the screenshot tool and it 
must be in blocking mode.&]
[s3; &]
[ {{10000F(128)G(128)@1 [s0;%% [* Public Method List]]}}&]
[s3; &]
[s5;:Upp`:`:DBusScreenshot`:`:Interactive`(bool`): DBusScreenshot[@(0.0.255) `&] 
[* Interactive]([@(0.0.255) bool] [*@3 b] [@(0.0.255) `=] [@(0.0.255) true])&]
[s2;%% If true, the portal will present the user with an interactive 
dialog allowing them to select an area, window, or specific screen 
to capture. If false, the portal attempts a silent, immediate 
screenshot. Interactive mode is enabled by default. Non`-interactive 
mode usually requires user/application privileges. Returns `*this 
for method chaining.&]
[s3;%% &]
[s4; &]
[s5;:Upp`:`:DBusScreenshot`:`:Modal`(bool`): DBusScreenshot[@(0.0.255) `&] 
[* Modal]([@(0.0.255) bool] [*@3 b] [@(0.0.255) `=] [@(0.0.255) true])&]
[s2;%% If true, the screenshot dialog is hinted to be modal to the 
application window. Modal mode is disabled by default. Returns 
`*this for method chaining.&]
[s3; &]
[s4; &]
[s5;:Upp`:`:DBusScreenshot`:`:RestoreToken`(const String`&`): DBusScreenshot[@(0.0.255) `&
] [* RestoreToken]([@(0.0.255) const] String[@(0.0.255) `&] [*@3 token])&]
[s2;%% Passes a previously acquired permission [%-*@3 token ]to the 
portal. If the token is valid and the user has previously granted 
permission, the portal can fulfill non`-interactive background 
screenshots silently without prompting the user. Returns `*this 
for method chaining.&]
[s3; &]
[s4; &]
[s5;:Upp`:`:DBusScreenshot`:`:Execute`(const String`&`): [@(0.0.255) bool] 
[* Execute]([@(0.0.255) const] String[@(0.0.255) `&] [*@3 parentwindow] 
[@(0.0.255) `=] [@(0.255.0) Null])&]
[s6;%% Requires a D`-Bus connection in blocking mode.&]
[s2;%% Requests the screenshot from the portal and suspends execution 
cleanly until the user completes the action. [%-*@3 parentwindow] 
can optionally pass the X11 XID or Wayland handle of the caller. 
Returns true if the screenshot was successfully taken and saved. 
Returns false if the user cancelled the dialog or an error occurred.&]
[s3; &]
[s4; &]
[s5;:Upp`:`:DBusScreenshot`:`:GetPath`(`)const: String [* GetPath]() 
[@(0.0.255) const]&]
[s2;%% Returns the absolute file path where the resulting screenshot 
was saved by the system. Returns Null if the operation failed 
or was cancelled.&]
[s3; &]
[s4; &]
[s5;:Upp`:`:DBusScreenshot`:`:GetRestoreToken`(`)const: String [* GetRestoreToken]() 
[@(0.0.255) const]&]
[s2;%% Returns the permission token generated by the desktop portal 
after a successful screenshot capture. If the application requires 
silent background screenshots in the future, client`-code should 
save this token string (e.g., to a configuration file) and pass 
it back via [C^topic`:`/`/DBusLib`/src`/DBusLib`_Screenshot`_en`-us`#Upp`:`:DBusScreenshot`:`:RestoreToken`(const String`&`)^ R
estoreToken()] in subsequent calls.&]
[s3; &]
[ {{10000F(128)G(128)@1 [s0;%% [* Function List]]}}&]
[s3;%% &]
[s5;:Upp`:`:TakeScreenshot`(DBusConnection`&`): String [* TakeScreenshot](DBusConnectio
n[@(0.0.255) `&] [*@3 dbus])&]
[s6;%% Requires a D`-Bus connection in blocking mode.&]
[s2;%% A convenience function to capture a screenshot. This function 
assumes interactive mode, therefore  the user is presented with 
the native screenshot selection dialog. Returns the absolute 
path to the saved screenshot image, or Null if cancelled.&]
[s3; &]
[ {{10000@(113.42.0) [s0;%% [*@7;4 D`-Bus Screenshot (Desktop Portal) Constants]]}}&]
[s3; &]
[s2; This group of constants defines the strings specified by the 
XDG Desktop Portal standard ([C@5 org.freedesktop.portal.Desktop]) 
for taking screenshots.&]
[s3; &]
[s4; &]
[s5;:Upp`:`:StdDBusScreenshotName: [@(0.0.255) constexpr] [@(0.0.255) const] 
[@(0.0.255) char] [@(0.0.255) `*][* StdDBusScreenshotName ]`= `"[C@5 org.freedesktop.port
al.Desktop`"]&]
[s2;%% The well`-known bus name of the XDG Desktop Portal service. 
Used as the destination service name when routing portal requests 
on the session bus.&]
[s3; &]
[s4; &]
[s5;:Upp`:`:StdDBusScreenshotPath: [@(0.0.255) constexpr] [@(0.0.255) const] 
[@(0.0.255) char] [@(0.0.255) `*][* StdDBusScreenshotPath ]`= `"[C@5 /org/freedesktop/por
tal/Desktop`"]&]
[s2;%% The standard object path implemented by the portal daemon 
for handling desktop interactions.&]
[s3; &]
[s4; &]
[s5;:Upp`:`:StdDBusScreenshotInterface: [@(0.0.255) constexpr] [@(0.0.255) const] 
[@(0.0.255) char] [@(0.0.255) `*][* StdDBusScreenshotInterface ]`= 
`"[C@5 org.freedesktop.portal.Screenshot`"]&]
[s2;%% The core interface implemented by the portal daemon for screenshot 
operations. Invoking the [C@5 Screenshot ]method on this interface 
triggers the native desktop capture utility.&]
[s0;%% ]]